baseURL: https://go-home.io
languageCode: en-us
title: go-home
enableGitInfo: true
menu: 
  main: 
    - identifier: docs
      name: Docs
      url: /docs/
      weight: 10
    - identifier: systems
      name: Systems
      url: /systems/
      weight: 20
    - identifier: apps
      name: Apps
      url: /apps/
      weight: 30
pygmentsStyle: dracula
pygmentsCodefences: true
pygmentsCodefencesGuessSyntax: true
blackfriday:
  hrefTargetBlank: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
outputs:
  home:
    - html
    - json