[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.57.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "https://go-home.io/x/providers/*"
to = "https://go-home.io/go/providers"
status = 301
force = true

[[redirects]]
from = "https://go-home.io/x/server/*"
to = "https://go-home.io/go/server"
status = 301
force = true