[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.45"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/providers/*"
to = "/providers"
status = 301
force = true